CREATE TABLE roles (
  ROLEID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ROLE VARCHAR(45) NOT NULL,
  PRIMARY KEY(ROLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;


CREATE TABLE userroles (
  USERID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ROLEID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(USERID, ROLEID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

alter table userroles add CONSTRAINT FK_Userroles_1 FOREIGN KEY (USERID) REFERENCES user (USERID);
alter table userroles add CONSTRAINT FK_Userroles_2 FOREIGN KEY (ROLEID)REFERENCES roles (ROLEID);

INSERT INTO roles (ROLE) VALUES ('beheerder');
INSERT INTO roles (ROLE) VALUES ('organisatiebeheerder');
INSERT INTO roles (ROLE) VALUES ('themabeheerder');
INSERT INTO roles (ROLE) VALUES ('gebruiker');
INSERT INTO roles (ROLE) VALUES ('demogebruiker');

INSERT INTO userroles (USERID, ROLEID) VALUES ('1', '1');


ALTER TABLE user DROP COLUMN ROLE;
