CREATE TABLE userip (
  USERIPID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USERID INTEGER UNSIGNED NOT NULL,
  IPADDRESS VARCHAR(45) NOT NULL,
  PRIMARY KEY(USERIPID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;


insert into userip (
  USERID,
  IPADDRESS
	)
  select 
  USERID,
  IPADDRESS
  from user;

alter table userip add CONSTRAINT FK_Userip_1 FOREIGN KEY (USERID) REFERENCES user (USERID);

ALTER TABLE user DROP COLUMN IPADDRESS;
