CREATE TABLE ipaddresses (
  IPADDRESSID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  IPADDRESS VARCHAR(45) NOT NULL,
  PRIMARY KEY(IPADDRESSID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;


CREATE TABLE userip (
  USERID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  IPADDRESSID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(USERID, IPADDRESSID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

alter table userip add CONSTRAINT FK_Userip_1 FOREIGN KEY (USERID) REFERENCES user (USERID);
alter table userip add CONSTRAINT FK_Userip_2 FOREIGN KEY (IPADDRESSID)REFERENCES ipaddresses (IPADDRESSID);

ALTER TABLE user DROP COLUMN ipaddress;