ALTER TABLE organization 
 MODIFY COLUMN STREET VARCHAR(50),
 MODIFY COLUMN NUMBER SMALLINT(5),
 MODIFY COLUMN PROVINCE VARCHAR(50),
 MODIFY COLUMN COUNTRY VARCHAR(50),
 MODIFY COLUMN POSTALCODE VARCHAR(45);
