ALTER TABLE `kaartenbalie_wis`.`organization` MODIFY COLUMN `STREET` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 0,
 MODIFY COLUMN `NUMBER` SMALLINT(5) DEFAULT 0,
 MODIFY COLUMN `PROVINCE` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 0,
 MODIFY COLUMN `COUNTRY` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT 0,
 MODIFY COLUMN `POSTALCODE` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci
, ROW_FORMAT = FIXED;
