CREATE TABLE `kaartenbalie`.`ipaddresses` (
  `IPADDRESSID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `IPADDRESS` VARCHAR(45) NOT NULL,
  PRIMARY KEY(`IPADDRESSID`)
)
ENGINE = InnoDB;

CREATE TABLE `kaartenbalie`.`userip` (
  `USERID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `IPADDRESSID` INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(`USERID`, `IPADDRESSID`),
  CONSTRAINT `FK_userip_1` FOREIGN KEY `FK_userip_1` (`USERID`)
    REFERENCES `user` (`USERID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_userip_2` FOREIGN KEY `FK_userip_2` (`IPADDRESSID`)
    REFERENCES `ipaddresses` (`IPADDRESSID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)